---
- name: disk demo
  hosts: servers
  become: true
  become_method: sudo
  tasks:

    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: Adding more space
      ansible.builtin.shell:
        cmd: /bin/echo 1 > sudo /sys/block/sda/device/rescan

    - name: Adding new partition
      ansible.builtin.shell:
        cmd: /bin/echo -e "d\n3\nn\n3\n\n\nN\nw" | sudo fdisk /dev/sda
