--- 
- hosts: servers
  become: true
  become_method: sudo 
  tasks: 
  
  - name: "Edit sshd_config"
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: PasswordAuthentication no
